name: client
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  provider: ^6.0.5
  collection: ^1.17.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.7
  http: ^1.1.0
  font_awesome_flutter: ^10.6.0
  window_manager: ^0.3.7
  flutter_screenutil: ^5.9.0
  flutter_custom_clippers: ^2.1.0
  desktop_webview_window: ^0.2.3
  infinite_scroll_pagination: ^4.0.0
  animated_theme_switcher: ^2.0.8
  jwt_decoder: ^2.0.1
  zxcvbn: ^1.0.0
  table_calendar: ^3.0.9
  webview_flutter: ^4.4.2
  flutter_quill: ^7.0.1
  go_router: ^11.1.4
  flutter:
    sdk: flutter
  intl: ^0.18.1
  url_launcher: ^6.1.14
  flutter_inappwebview: ^5.8.0
  flutter_web_auth: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
